version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - '9090:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
