FROM node:current-alpine as walrus-frontend-build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json

RUN yarn install --silent

COPY . /app

RUN yarn build

FROM nginx:mainline-alpine

COPY nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=walrus-frontend-build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
