version: "3.7"

services:
  walrusapp:
    build:
      context: .
    ports:
      - "8020:80"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
